### ISSUE TITLE
Epic: General Requirements

### ISSUE THREAD

**Issue by QuentinCovert** [QuentinCovert/SyncOrSwim#24]
- [x] Set Remote File System
- [ ] Auto-Sync Files
- [x] Record Viewing
- [ ] Update Local Files
- [x] Multiple Root Tree Monitoring
- [x] Encryption Off Functionality
- [ ] Ignore Files
