### ISSUE TITLE
Epic: Crypto Module

### ISSUE THREAD

**Issue by QuentinCovert** [QuentinCovert/SyncOrSwim#33]
- [ ] Change Max Auto-Encryption Size
- [ ] Auto-Encrypt Synced Files
- [ ] Auto-Decrypt Files
- [x] Decrypt Files
- [ ] Suto-Encrypt Files
- [x] Encrypt Files
- [ ] Auto-Generate Encryption Key
- [x] Generate Encryption Key
