### ISSUE TITLE
Epic: Database

### ISSUE THREAD

**Issue by QuentinCovert** [QuentinCovert/SyncOrSwim#81]
- [x] SQLite Database that stores files and:
- [x] Stores a local path for the file
- [x] Stores the path on the remote sync
- [x] Stores a record of the time the file was modified
- [x] Stores the encryption status of each file
- [x] Stores path to encrypted file
