### ISSUE TITLE
Epic: Filesystem Structure

### ISSUE THREAD

**Issue by LostLaplace** [QuentinCovert/SyncOrSwim#83]
- [x] Generate FSO Tree
- [x] Add file to tree
- [x] Remove file from tree
- [x] Find file from relative path
